### ISSUE TITLE
dpad. when quick switch on listview or gridview ,it's hightlighting multiple items

### ISSUE THREAD

**Issue by y3l1n4ung** [nicoaudy/dpad_container#2]
dpad. when quick move up/down or left/right on listview or grid view ,it's highlighting multiple items,

**Comment by nicoaudy** [comment]
Ah! Can i get some gif screenshot about this issue?

**Comment by y3l1n4ung** [comment]
[`image one`](https://ibb.co/Z6QbVmv)
[`image two`](https://ibb.co/hKxPPVG)

**Comment by y3l1n4ung** [comment]
here is gif , tested with an example code [`gif`](https://ibb.co/nQsVh6p)

**Comment by scottie612** [comment]
Any update?

**Comment by y3l1n4ung** [comment]
don't use this plugin,just use inkwell and use onFcous
