### ISSUE TITLE
Weird behaviour when we press right / left  and then go up/down.

### ISSUE THREAD

**Issue by wintuvogga** [nicoaudy/dpad_container#3]
Issue: 
I have column of widgets. 
few TextFormFields and Switches and buttons.
so I can go up and down through the navigation very nicely.
also select items nicely.
But the issue happens when I go right / left and then and go up/down.
Some times textboxes gets focus and some times multiple items gets focus.
This issue doe not happen if I never press right/left. 

code is here:

`import 'dart:io';

import 'package:date_format/date_format.dart';
import 'package:flutter/material.dart';
import 'package:flutter/src/foundation/key.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:provider/provider.dart';
import 'package:st_pids/logics/apiintegrations.dart';
import 'package:st_pids/logics/settings.dart';
import 'components/popup.dart';
import 'package:dpad_container/dpad_container.dart';
import 'logics/screenratios.dart';

TextEditingController stopcodetextcontroller = TextEditingController();
TextEditingController mediaDurationTextController = TextEditingController();
TextEditingController quickestWayTextController = TextEditingController();
TextEditingController mrtRadiusTextController = TextEditingController();

String currentStopCode = "";
String mediaDuration = "";
String quickestDuration = "";
String mrtScanRadius = "";

class SettingsManager extends StatefulWidget {
  SettingsManager({Key? key}) : super(key: key);

  @override
  State<SettingsManager> createState() => _SettingsManagerState();
}

class _SettingsManagerState extends State<SettingsManager> {
  @override
  Widget build(BuildContext context) {
    return SafeArea(
        top: Platform.isIOS ? true : false,
        bottom: Platform.isIOS ? true : false,
        child: SettingsWidget(context.watch<Settings>()));
  }
}

class SettingsWidget extends StatefulWidget {
  SettingsWidget(this.settings, {Key? key}) : super(key: key);

  Settings settings = Settings();
  bool displayMode = false;
  bool scrolling = false;
  bool muted = false;
  @override
  State<SettingsWidget> createState() => _SettingsWidgetState();
}

class _SettingsWidgetState extends State<SettingsWidget> {
  bool saveButtonHasFocus = false;
  bool cancelButtonHasFocus = false;
  bool stopTextBoxHasFocus = false;
  bool mediaDurationHasFocus = false;
  bool quickestWayHasFocus = false;
  bool dispOrientataionHasFocus = false;
  bool paginScrollingHasFocus = false;
  bool autoMutedHadFocus = false;
  bool mrtRadiusHasFocus = false;
  late FocusNode stopCodeFocusNode;
  late FocusNode mediaDurationFocusNode;
  late FocusNode quickestWayDurationFocusNode;
  late FocusNode sacnRadiusFocusNode;
  late FocusNode mrtRadiusFocusNode;

  Color? buttonColor = Colors.transparent;
  Color? buttonFocusedColor = Colors.white;
  Color? buttonTextFocusColor = Colors.black;
  Color? buttonTextColor = Colors.white;

  @override
  void initState() {
    stopcodetextcontroller = TextEditingController();
    mediaDurationTextController = TextEditingController();
    quickestWayTextController = TextEditingController();
    stopCodeFocusNode = FocusNode();
    mediaDurationFocusNode = FocusNode();
    quickestWayDurationFocusNode = FocusNode();
    sacnRadiusFocusNode = FocusNode();
    mrtRadiusFocusNode = FocusNode();
    widget.displayMode =
        widget.settings.screenorientation == ScreenOrientation.vertical
            ? false
            : true;
    widget.scrolling =
        widget.settings.scrolling == ETAScrollingOrPageing.scrolling
            ? false
            : true;
    widget.muted = widget.settings.audioMute == 0 ? false : true;
    mediaDurationTextController.text =
        widget.settings.mediaDisplayDuration.toString();
    quickestWayTextController.text =
        widget.settings.quickestWayToDuration.toString();
    stopcodetextcontroller.text = widget.settings.systemStopCode;
    currentStopCode = widget.settings.systemStopCode;
    mediaDuration = widget.settings.mediaDisplayDuration.toString();
    quickestDuration = widget.settings.quickestWayToDuration.toString();
    mrtRadiusTextController.text = widget.settings.mrtRadius.toString();
    mrtScanRadius = widget.settings.mrtRadius.toString();
    super.initState();
  }

  @override
  void dispose() {
    stopCodeFocusNode.dispose();
    super.dispose();
  }

  Widget getTextField(String label, TextEditingController controller, Icon icon,
      String currentValue, bool hasFocus, FocusNode focusNode) {
    return Container(
      width: ScreenRatio().topBarWidth() * 0.7,
      margin: EdgeInsets.all(ScreenRatio().padding() * 2),
      decoration: BoxDecoration(
          color: hasFocus
              ? const Color.fromARGB(255, 90, 89, 89)
              : const Color.fromARGB(255, 70, 55, 55),
          borderRadius: const BorderRadius.all(Radius.circular(5))),
      child: TextFormField(
        focusNode: focusNode,
        keyboardType: TextInputType.number,
        controller: controller,
        style: TextStyle(
            color: Colors.white, fontSize: ScreenRatio().topBarFontSize()),
        decoration: InputDecoration(
          prefixIcon: icon, //Icon(Icons.bus_alert_sharp),
          prefixIconColor: Colors.white,
          border: const UnderlineInputBorder(),
          labelText: '$label $currentValue',
          labelStyle: const TextStyle(
              fontSize: 20, color: Color.fromARGB(255, 44, 173, 18)),
        ),
      ),
    );
  }

  Widget getSwitch(String labelTrue, String labelFalse, bool flag,
      bool hasFocus, Function(bool) onChanged) {
    return Container(
        width: ScreenRatio().topBarWidth() * 0.7,
        margin: EdgeInsets.all(ScreenRatio().padding() * 2),
        decoration: BoxDecoration(
            color: hasFocus
                ? Color.fromARGB(255, 119, 116, 116)
                : Color.fromARGB(255, 70, 55, 55),
            borderRadius: BorderRadius.all(Radius.circular(5))),
        child: Row(mainAxisAlignment: MainAxisAlignment.spaceEvenly, children: [
          Text(
            flag ? labelTrue : labelFalse,
            style: TextStyle(
                color: Colors.white, fontSize: ScreenRatio().topBarFontSize()),
          ),
          Switch(
            value: flag,
            onChanged: onChanged,
            activeTrackColor: Colors.lightGreenAccent,
            activeColor: Colors.green,
            inactiveTrackColor: Colors.red,
          ),
        ]));
  }

  Future<void> saveSettings() async {
    ScreenOrientation ori = ScreenOrientation.vertical;
    if (widget.displayMode) {
      ori = ScreenOrientation.horizonal;
    }

    ETAScrollingOrPageing scrol = ETAScrollingOrPageing.scrolling;
    if (widget.scrolling) {
      scrol = ETAScrollingOrPageing.paging;
    }

    var resp = await ApiIntegration().getSopName(stopcodetextcontroller.text);

    int audio = 0;
    if (widget.muted) {
      audio = 1;
    }

    if (resp[0] == false) {
      await areYouSurePopup(
          "Sorry, code ${stopcodetextcontroller.text} is not valid",
          context,
          ScreenRatio().messageBoxWidth(),
          ScreenRatio().messageBoxHeight());
    } else {
      await widget.settings.save(
          ori,
          stopcodetextcontroller.text,
          scrol,
          int.parse(mediaDurationTextController.text),
          int.parse(quickestWayTextController.text),
          audio,
          int.parse(mrtRadiusTextController.text));
      ApiIntegration().refreshNow();
      Navigator.of(context).pop();
    }
  }

  @override
  Widget build(BuildContext context) {
    Settings settings = context.watch<Settings>();
    ScreenRatio().init(context, settings.screenorientation);

    return Scaffold(
        backgroundColor: Colors.black,
        body: SingleChildScrollView(
            child: Column(
          children: [
            const SizedBox(
              height: 10,
            ),
            Container(
              width: ScreenRatio().topBarWidth() / 2,
              height: ScreenRatio().topBarHeight(),
              decoration: const BoxDecoration(
                color: Colors.redAccent,
                borderRadius: BorderRadius.all(Radius.circular(5)),
              ),
              alignment: Alignment.center,
              child: Text(
                "Settings",
                style: TextStyle(
                    color: Colors.white,
                    fontSize: ScreenRatio().topBarFontSize()),
              ),
            ),
            DpadContainer(
                onClick: () {
                  stopCodeFocusNode.requestFocus();
                },
                onFocus: (focus) {
                  setState(() {
                    stopTextBoxHasFocus = focus;
                  });
                },
                child: getTextField(
                    'Current Stop:',
                    stopcodetextcontroller,
                    const Icon(Icons.bus_alert_sharp),
                    currentStopCode,
                    stopTextBoxHasFocus,
                    stopCodeFocusNode)),
            DpadContainer(
                onClick: () {
                  mediaDurationFocusNode.requestFocus();
                },
                onFocus: (focus) {
                  setState(() {
                    mediaDurationHasFocus = focus;
                  });
                },
                child: getTextField(
                    'Media duration:',
                    mediaDurationTextController,
                    const Icon(Icons.punch_clock),
                    mediaDuration,
                    mediaDurationHasFocus,
                    mediaDurationFocusNode)),
            DpadContainer(
                onClick: () {
                  quickestWayDurationFocusNode.requestFocus();
                },
                onFocus: (focus) {
                  setState(() {
                    quickestWayHasFocus = focus;
                  });
                },
                child: getTextField(
                    'QuickWay duration:',
                    quickestWayTextController,
                    const Icon(Icons.punch_clock),
                    quickestDuration,
                    quickestWayHasFocus,
                    quickestWayDurationFocusNode)),
            DpadContainer(
                onClick: () {
                  mrtRadiusFocusNode.requestFocus();
                },
                onFocus: (focus) {
                  setState(() {
                    mrtRadiusHasFocus = focus;
                  });
                },
                child: getTextField(
                    'Scan Radius(m):',
                    mrtRadiusTextController,
                    const Icon(Icons.circle_rounded),
                    mrtScanRadius,
                    mrtRadiusHasFocus,
                    mrtRadiusFocusNode)),
            DpadContainer(
                onClick: () {
                  setState(() {
                    widget.displayMode = !widget.displayMode;
                  });
                },
                onFocus: (focus) {
                  setState(() {
                    dispOrientataionHasFocus = focus;
                  });
                },
                child: getSwitch("Landscape", "Portrait", widget.displayMode,
                    dispOrientataionHasFocus, (value) {
                  {
                    setState(() {
                      widget.displayMode = value;
                    });
                  }
                })),
            DpadContainer(
                onClick: () {
                  setState(() {
                    widget.scrolling = !widget.scrolling;
                  });
                },
                onFocus: (focus) {
                  setState(() {
                    paginScrollingHasFocus = focus;
                  });
                },
                child: getSwitch("Paging", "Scrolling", widget.scrolling,
                    paginScrollingHasFocus, (value) {
                  {
                    setState(() {
                      widget.scrolling = value;
                    });
                  }
                })),
            DpadContainer(
                onClick: () {
                  setState(() {
                    widget.muted = !widget.muted;
                  });
                },
                onFocus: (focus) {
                  setState(() {
                    autoMutedHadFocus = focus;
                  });
                },
                child: getSwitch(
                    "Audio OFF", "Audio ON", widget.muted, autoMutedHadFocus,
                    (value) {
                  {
                    setState(() {
                      widget.muted = value;
                    });
                  }
                })),
            Row(
              mainAxisAlignment: MainAxisAlignment.spaceEvenly,
              children: [
                const SizedBox(
                  width: 20,
                ),
                DpadContainer(
                    onClick: () {
                      saveSettings();
                    },
                    onFocus: (focus) {
                      setState(() {
                        saveButtonHasFocus = focus;
                      });
                    },
                    child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                            primary: saveButtonHasFocus
                                ? buttonFocusedColor
                                : buttonColor),
                        onPressed: () async {
                          saveSettings();
                        },
                        child: Text("Save",
                            style: TextStyle(
                                color: saveButtonHasFocus
                                    ? buttonTextFocusColor
                                    : buttonTextColor)))),
                DpadContainer(
                    onClick: () {
                      Navigator.of(context).pop();
                    },
                    onFocus: (focus) {
                      setState(() {
                        cancelButtonHasFocus = focus;
                      });
                    },
                    child: ElevatedButton(
                        onPressed: () {
                          Navigator.of(context).pop();
                        },
                        style: ElevatedButton.styleFrom(
                            primary: cancelButtonHasFocus
                                ? buttonFocusedColor
                                : buttonColor),
                        child: Text(
                          "Cancel",
                          style: TextStyle(
                              color: cancelButtonHasFocus
                                  ? buttonTextFocusColor
                                  : buttonTextColor),
                        ))),
                const SizedBox(
                  width: 20,
                )
              ],
            ),
            const SizedBox(
              height: 40,
            )
          ],
        )));
  }
}
`

**Comment by nicoaudy** [comment]
Hi @wintuvogga, I manage to fix this issue on this commit https://github.com/nicoaudy/dpad_container/commit/19ecad3f4da3ce039c37a593721bb0ee90fb6e35

**Comment by wintuvogga** [comment]
Thank you @nicoaudy ..
