### ISSUE TITLE
Is it possible to open the keyboard when text field is focus using focus Node ?

### ISSUE THREAD

**Issue by amirVirtuenetz** [nicoaudy/dpad_container#4]
I am using the Shortcuts in the parent widget tree.
the sample code is below:
ActionHandler().handleArrowAndEnterAction(
 Padding(
                                    padding: EdgeInsets.symmetric(
                                        horizontal: 15.w, vertical: 5.h),
                                    child: ActionWidget(
                                      focusNode: _passwordFocusNode!,
                                      actions: {
                                        ArrowDownButtonIntent: CallbackAction<
                                            ArrowDownButtonIntent>(
                                          onInvoke: (intent) {
                                            _passwordFocusNode?.unfocus();
                                            return changeFocus(
                                                context, _loginBtnFocusNode!);
                                          },
                                        ),
                                        ArrowUpButtonIntent:
                                            CallbackAction<ArrowUpButtonIntent>(
                                          onInvoke: (intent) {
                                            _passwordFocusNode?.unfocus();
                                            log("focus shift to email field");
                                            return changeFocus(
                                                context, _emailFocusNode!);
                                          },
                                        ),
                                        EnterButtonIntent:
                                            CallbackAction<EnterButtonIntent>(
                                          onInvoke: (intent) {
                                            log("Focus on Password textfield");
                                            return
                                                // _passwordFocusNode
                                                //   ?.requestFocus();
                                                // FocusScopeNode(
                                                //   canRequestFocus: true);
                                                changeFocus(context,
                                                    _passwordFocusNode!);
                                          },
                                        ),
                                      },
                                      child: CustomTextField(
                                          // autoFocus: true,
                                          // onTap: () => _passwordFocusNode
                                          //     ?.requestFocus(),
                                          // !(_passwordFocusNode?.hasFocus ??
                                          //         false)
                                          //     ? true
                                          //     : false,
                                          focusNode: _passwordFocusNode,
                                          placeHolder: 'Password',
                                          controller: loginController
                                              .passwordController,
                                          textInputAction: TextInputAction.done,
                                          // height: 20,
                                          // errorText: loginController
                                          //         .passwordErrorText
                                          //         .value
                                          //         .isEmpty
                                          //     ? ""
                                          //     : loginController
                                          //         .passwordErrorText.value,
                                          borderRadius: 100,
                                          borderColor:
                                              // !(_passwordFocusNode?.hasFocus ??
                                              //         false)
                                              //     ?
                                              Colors.blueAccent,
                                          // : Colors.white,
                                          obscureText:
                                              obscureText, //obscureText,
                                          isPrefixEnabled: false,
                                          changeObscureText: () {
                                            setState(() {
                                              obscureText = !obscureText;
                                            });
                                          },
                                          // prefixIcon: Icons.lock_rounded,
                                          isSuffixEnabled: true,
                                          suffixIcon: obscureText == true
                                              ? showPasswordSVG
                                              : hidePasswordSVG,
                                          onChangeText: (String str) {
                                            setState(() {
                                              password = str;
                                            });
                                            // log(password);
                                          }),
                                    ),
                                  ),
                                  ),
                                  
         this ActionHandler class is below:
         class ActionHandler {
  Widget handleArrowAndEnterAction({required Widget child}) {
    return Shortcuts(shortcuts: <LogicalKeySet, Intent>{
      LogicalKeySet(
        LogicalKeyboardKey.arrowLeft,
      ): LeftButtonIntent(),
      LogicalKeySet(
        LogicalKeyboardKey.arrowRight,
      ): RightButtonIntent(),
      LogicalKeySet(
        LogicalKeyboardKey.arrowUp,
      ): ArrowUpButtonIntent(),
      LogicalKeySet(
        LogicalKeyboardKey.arrowDown,
      ): ArrowDownButtonIntent(),
      LogicalKeySet(
        LogicalKeyboardKey.select,
      ): EnterButtonIntent(),
    }, child: child);
  }
}

**Comment by nicoaudy** [comment]
Hi @amirVirtuenetz, you can do anything with dpad_container. There's an onClick and onFocus handler, I believe when there's an onClick or onFocus event you can open your keyboard

**Comment by amirVirtuenetz** [comment]
> Hi @amirVirtuenetz, you can do anything with dpad_container. There's an onClick and onFocus handler, I believe when there's an onClick or onFocus event you can open your keyboard

Hi @nicoaudy I have implemented the package example it is work fine when list or grid item
but I have different scenario .

scenario 1: according to your example in the repository

class Example extends StatefulWidget {
  const Example({Key? key}) : super(key: key);

  @override
  State<Example> createState() => _ExampleState();
}

class _ExampleState extends State<Example> {
  int? selectedIndex;
  int? onFocusIndex;
  FocusNode? focusNode;

  @override
  Widget build(BuildContext context) {
    return ListView.builder(
      primary: false,
      padding: const EdgeInsets.all(10),
      itemCount: 3,
      itemBuilder: (ctx, i) {
        return DpadContainer(
          onClick: () => setState(() {
            selectedIndex = i;
          }),
          onFocus: (bool isFocused) {
            setState(() => onFocusIndex = i);
          },
          child: Container(
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(10),
              color: onFocusIndex == i ? Colors.white : Colors.grey,
              border: Border.all(
                color: onFocusIndex == i
                    ? Colors.white
                    : (selectedIndex == i
                        ? Colors.blue.shade400
                        : Colors.black),
                width: 5,
              ),
              // image: DecorationImage(
              //     image: NetworkImage(image), fit: BoxFit.cover),
            ),
            child: CustomTextField(
              focusNode: focusNode,
              onChangeText: (val) {},
              onSubmit: (String value) {},
            ),
          ),
        );
      },
    );
  }
}

I have put the text field in the listview builder . it is move to next TextField properly but when i click the enter button from the d-pad, the keyboard not opened.
scenario 1: I have TextField and 4 buttons that in a row and column.
when I focus the first text field and press enter button from d-pad , the TextField opened and when enter some text on it affter unfous the TextField the foucs will shift to next text field after putting some data the Focus will shift to next button
and move on
is it possible, how can I achieve this? 
the below picture is described clearly about my scenario.
i hope you will clear about that
![scenario](https://user-images.githubusercontent.com/102783192/217156634-3e7ae2c0-c401-4a35-943c-29bd0a3e1e57.png)
