### ISSUE TITLE
Not Working on web

### ISSUE THREAD

**Issue by AhmadKahlid** [nicoaudy/dpad_container#5]
This package is not working with flutter web
 
Steps to reproduce:

- Download example from this repo.
- Run ``` flutter create . ``` to add required web files to project.
- Run ``` flutter clean ``` then ``` flutter pub get ```.
- Run ``` flutter run -d chrome ```

Flutter (Channel stable, 3.3.10, on macOS 13.1 22C65 darwin-arm)

**Comment by nicoaudy** [comment]
@AhmadKahlid  the package is not tested on the web, the purpose of the package is only to run on TV. Thanks
