### ISSUE TITLE
Gridviews

### ISSUE THREAD

**Issue by Yoda-Man** [nicoaudy/dpad_container#6]
How do we highlight selected items in a gridview? I dont see what has the focus in my emulator.

**Comment by nicoaudy** [comment]
Hi Yoda, can you drop your code here? so I can reproduce the issue.

Thanks

**Comment by Yoda-Man** [comment]
import 'dart:math';

import 'package:dpad_container/dpad_container.dart';
import 'package:flutter/material.dart';

import '../key.dart';
import '../model/authentication.dart';
import '../model/content.dart';
import '../model/startupdata.dart';
import 'dialogbox.dart';

class TVMenu extends StatefulWidget {
  const TVMenu({super.key});

  @override
  State<TVMenu> createState() => TVMenuState();
}

class TVMenuState extends State<TVMenu> {
  @override
  Future<void> action(int index) async {
    switch (index) {
      case 0:
        if (currentuser.userID.isEmpty) {
          dialogbox(context, title, 'Please sign in to use this feature.');
          return;
        } else {
          Navigator.pushNamed(
            context,
            '/ChangePasswordPage',
          );
        }
        break;
      case 1:
        if (currentuser.userID.isEmpty) {
          dialogbox(context, title, 'Please sign in to use this feature.');
          return;
        } else {
          if (player.currentIndex != null) player.dispose();
          audioPageTitle = 'My Super Mix';
          await setPlaylist();
          current.submissionid = '';
          Navigator.pushNamed(
            context,
            '/SingleAudioPage',
          );
        }
        break;
      case 2:
        if (player.currentIndex != null) player.dispose();
        audioPageTitle = 'Discover Weekly';
        await setPlaylist();
        current.submissionid = '';

        if (currentPlaylist.isEmpty) {
          Navigator.pushNamed(
            context,
            '/AudioPage',
          );
        } else {
          Navigator.pushNamed(
            context,
            '/SingleAudioPage',
          );
        }
        break;
      case 3:
        audioPageTitle = 'Radio';
        Random rnd = Random();
        int nextTrack = 1 + rnd.nextInt(38 - 1);
        await setPlaylist();

        play(playlistTracks[nextTrack], context);
        break;

      case 4:
        customBottomSheet(context);
        break;
      default:
        signout();
        Navigator.pushNamed(
          context,
          '/LoginPage',
        );
        break;
    }
  }

  Widget build(BuildContext context) {
    return SizedBox(
        width: 200.0,
        child: ListView(
          scrollDirection: Axis.vertical,
          children: <Widget>[
            Visibility(
                visible: (!currentuser.userID.isEmpty),
                child: DpadContainer(
                    onClick: () {
                      action(0);
                    },
                    onFocus: (bool isFocused) {},
                    child: ListTile(
                      minLeadingWidth: 0,
                      horizontalTitleGap: 2,
                      leading: CircleAvatar(
                        radius: 26,
                        backgroundImage: NetworkImage(
                          currentuser.photoURL,
                        ),
                      ),
                      onTap: () => action(0),
                      title: Text(currentuser.firstName,
                          style: const TextStyle(
                              color: Colors.white,
                              fontWeight: FontWeight.bold)),
                    ))),
            const SizedBox(height: 8.0),
            DpadContainer(
                onClick: () async {
                  action(1);
                },
                onFocus: (bool isFocused) {},
                child: ListTile(
                  minLeadingWidth: 0,
                  horizontalTitleGap: 2,
                  onTap: () => action(1),
                  leading: const Icon(
                    Icons.audiotrack,
                    color: Colors.white,
                  ),
                  title: const Text('My Super Mix',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                )),
            const SizedBox(height: 4.0),
            DpadContainer(
                onClick: () async {
                  action(2);
                },
                onFocus: (bool isFocused) {},
                child: ListTile(
                  minLeadingWidth: 0,
                  horizontalTitleGap: 2,
                  onTap: () => action(2),
                  leading:
                      const Icon(Icons.explore_outlined, color: Colors.white),
                  title: const Text('Discover Weekly',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                )),
            const SizedBox(height: 4.0),
            DpadContainer(
                onClick: () async {
                  action(3);
                },
                onFocus: (bool isFocused) {},
                child: ListTile(
                  minLeadingWidth: 0,
                  horizontalTitleGap: 2,
                  onTap: () => action(3),
                  leading: const Icon(Icons.library_music_outlined,
                      color: Colors.white),
                  title: const Text('Play Something',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                )),
            const SizedBox(height: 4.0),
            DpadContainer(
                onClick: () {
                  action(4);
                },
                onFocus: (bool isFocused) {},
                child: ListTile(
                  minLeadingWidth: 0,
                  horizontalTitleGap: 2,
                  onTap: () => action(4),
                  leading: const Icon(Icons.lock_open, color: Colors.white),
                  title: const Text('Access Codes',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                )),
            const SizedBox(height: 4.0),
            DpadContainer(
                onClick: () {
                  action(5);
                },
                onFocus: (bool isFocused) {},
                child: ListTile(
                  minLeadingWidth: 0,
                  horizontalTitleGap: 2,
                  onTap: () => action(5),
                  leading: const Icon(Icons.login, color: Colors.white),
                  title: const Text('Sign In',
                      style: TextStyle(
                          color: Colors.white, fontWeight: FontWeight.bold)),
                )),
            const SizedBox(height: 4.0),
            const Image(
              image: AssetImage('assets/4.png'),
              fit: BoxFit.scaleDown,
            ),
          ],
        ));
  }
}

**Comment by Yoda-Man** [comment]
import 'package:dpad_container/dpad_container.dart';

import '../model/content.dart';
import 'package:flutter/material.dart';
import '../model/startupdata.dart';

class PlayList3GridView extends StatelessWidget {
  final List<Content> tracks;

  const PlayList3GridView({Key? key, required this.tracks}) : super(key: key);
  DpadContainer getStructuredGridCell(Content? track, BuildContext context) {
    return DpadContainer(
        onClick: () async {
          audioPageTitle = 'Radio';
          await setPlaylist();
          play(track, context);
        },
        onFocus: (bool isFocused) {},
        child: Card(
            elevation: 1.5,
            color: Colors.black,
            child: InkResponse(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisSize: MainAxisSize.min,
                verticalDirection: VerticalDirection.down,
                children: <Widget>[
                  ConstrainedBox(
                    constraints: const BoxConstraints(
                      minWidth: 260,
                      minHeight: 180,
                      maxWidth: 270,
                      maxHeight: 190,
                    ),
                    child: Image.network(track!.coverart, fit: BoxFit.cover),
                  ),
                  Padding(
                    padding: const EdgeInsets.only(left: 10.0),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: <Widget>[
                        Text(track.title,
                            style: const TextStyle(color: Colors.white)),
                        Row(
                          crossAxisAlignment: CrossAxisAlignment.center,
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            Text(track.artist,
                                style: const TextStyle(
                                    color: Colors.white,
                                    fontWeight: FontWeight.bold)),
                            const SizedBox(
                              width: 5,
                            ),
                            Icon(iconMapping[track.submissionType],
                                color: Colors.white, size: 26)
                          ],
                        )
                      ],
                    ),
                  )
                ],
              ),
              onTap: () async {
                audioPageTitle = 'Radio';
                await setPlaylist();
                play(track, context);
              },
            )));
  }

  @override
  Widget build(BuildContext context) {
    return GridView.count(
      primary: true,
      scrollDirection: Axis.horizontal,
      crossAxisCount: 1,
      childAspectRatio: 0.90,
      children: List.generate(tracks.length, (index) {
        return getStructuredGridCell(tracks[index], context);
      }),
    );
  }
}

**Comment by nicoaudy** [comment]
You need 1 state for the focus node, every time the onFocus trigger set your state to focus and you can do like if the node is focused change the color to white. Please take a look at this example https://github.com/nicoaudy/dpad_container/blob/main/example/lib/main.dart
