### ISSUE TITLE
dpad select button causing double click events.

### ISSUE THREAD

**Issue by devnullpointer** [nicoaudy/dpad_container#7]
Implemented the dpad_container as per instructions, and have a simple log on the onClick parameter, I'm getting double the log events for the click and single for the focus.

DpadContainer(
    onClick: () {logDebug('Dpad Container onClick event. Widget: Search');},
          onFocus: (isFocused) {
            logDebug('Focus event: $isFocused');
            setState(() => {_focusItem = AppBarItems.search});
          },
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 12),
            child: IconButton(
              focusColor: const Color(JBColors.transparentAccent),
              icon: const Icon(Icons.search),
              onPressed: () {},
            ),
          )
        ),

Logs:

Performing hot reload...
Syncing files to device Android SDK built for x86...
Reloaded 1 of 1026 libraries in 549ms (compile: 43 ms, reload: 243 ms, reassemble: 227 ms).
I/flutter ( 8383): 🐛 14:39:13.755608 DEBUG    Global Loggy - Focus event: false
I/flutter ( 8383): 🐛 14:39:18.175485 DEBUG    Global Loggy - Focus event: true
I/flutter ( 8383): 🐛 14:39:26.570691 DEBUG    Global Loggy - Dpad Container onClick event. Widget: Search
I/flutter ( 8383): 🐛 14:39:26.679756 DEBUG    Global Loggy - Dpad Container onClick event. Widget: Search

**Comment by nicoaudy** [comment]
Hi @devnullpointer, i have take a look the issue and i manage to fixed the issue. You can update your package to the latest version `2.0.4`. Thanks👋

**Comment by shtreb** [comment]
@nicoaudy It still reproducing with Icon button on my TV box X96
