### ISSUE TITLE
More Examples (sidebar, switch )

### ISSUE THREAD

**Issue by michalss** [nicoaudy/dpad_container#8]
Hi,

Can you please add more samples with multiple Containers. For example how you would handle TextFields, swicthes or if you have an SideBar or Drawer and content area, to handle navigation between them. This is most important things for ATV.

thank you

**Comment by rednikisfun** [comment]
That would actually be very helpful. I am trying to use NavigationRail as my menu, and I don't really understand how can I use it to easily manipulate between the menu and the page items correctly. 

Thank you!
