### ISSUE TITLE
onClick currently not working?

### ISSUE THREAD

**Issue by albrnick** [nicoaudy/dpad_container#9]
Hello!  

First off, love the library!  So easy! = )

I have a weird issue.  Pressing the center button/click doesn't seem to be working for me.  Emulating using "Android TV 1080p API 28", and the d-pad.

Doing debugging, I'm not even getting an event in 'onKey' function of the RawKeyboardListener used DpadContainer.

(Also, minor thing, is it possible to be able to pass in a focus node? I need to get at the focus node for scrolling)

Thanks for your time!
Nick

**Comment by nicoaudy** [comment]
Hi! can you give a minimal code to reproduce the `issue`, or you can see the example folder how to use this container nodes.  You can do with current function for example

```
onFocus: (bool isFocused) {
 setState(() => onFocusIndex = i);
 
 // call another method/action you want
}
```

**Comment by albrnick** [comment]
Hello! Thanks

**Comment by albrnick** [comment]
(Ops! Hit wrong button and closed)

Thanks for the quick response! Turns out it was an issue with the way I was building the grid.  Once I fixed that, everything behaves as expected. Sorry about that!
